### ISSUE TITLE
Disconnected crashes

### ISSUE THREAD

**Issue by jihopark** [realtime-framework/RealtimeMessaging-ReactNativeAndroidExample#4]
```
E/unknown:React(24448): java.lang.NullPointerException
E/unknown:React(24448):     at ibt.ortc.extensibility.OrtcClient.disconnect(OrtcClient.java:381)
E/unknown:React(24448):     at co.realtime.reactnativemessagingandroid.RealtimeMessagingAndroid.disconnect(RealtimeMessagingAndroid.java:218)
E/unknown:React(24448):     at java.lang.reflect.Method.invokeNative(Native Method)
E/unknown:React(24448):     at java.lang.reflect.Method.invoke(Method.java:515)
E/unknown:React(24448):     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
E/unknown:React(24448):     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:140)
E/unknown:React(24448):     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
E/unknown:React(24448):     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:378)
E/unknown:React(24448):     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
E/unknown:React(24448):     at android.os.Handler.handleCallback(Handler.java:733)
E/unknown:React(24448):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:React(24448):     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
E/unknown:React(24448):     at android.os.Looper.loop(Looper.java:136)
E/unknown:React(24448):     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
E/unknown:React(24448):     at java.lang.Thread.run(Thread.java:841)
D/dalvikvm(24448): GC_CONCURRENT freed 516K, 8% free 7696K/8288K, paused 0ms+1ms, total 5ms
```

The connect and subscribe works, but then disconnect crashes

**Comment by JoaoCaixinha** [comment]
Hi, thanks for reporting this problem, check version 1.0.4.

**Comment by realtime-framework** [comment]
Fixed by https://github.com/realtime-framework/RCTRealtimeMessagingAndroid/commit/552ee2a46b1f5953e0e2bd449f71f15dc67ad478
